/**
 * vastlint C API
 *
 * Validate IAB VAST XML tags from any language that can call a C library.
 *
 * Quick start:
 *
 *   VastlintResult *r = vastlint_validate(xml, 0);
 *   if (vastlint_result_valid(r)) {
 *     // tag is clean
 *   } else {
 *     const char *json = vastlint_result_json(r);
 *     // parse json to get issue details
 *   }
 *   vastlint_result_free(r);
 *
 * All functions are thread-safe and re-entrant except vastlint_result_free,
 * which must not be called concurrently on the same pointer.
 *
 * This file is auto-generated by cbindgen. To regenerate:
 *   cbindgen --config crates/vastlint-ffi/cbindgen.toml \
 *             --crate vastlint-ffi \
 *             --output crates/vastlint-ffi/vastlint.h
 */

#ifndef VASTLINT_H
#define VASTLINT_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Opaque handle to a validation result. Use the accessor functions below;
 * do not inspect the struct contents directly. Free with vastlint_result_free.
 */
typedef struct VastlintResult VastlintResult;

/**
 * Validate a VAST XML string.
 *
 * xml     - pointer to a UTF-8 string (null-terminated).
 * xml_len - byte length of xml, not including the null terminator.
 *           Pass 0 to have this function compute the length via strlen.
 *
 * Returns a pointer to a VastlintResult that the caller MUST free with
 * vastlint_result_free. Returns NULL if xml is NULL.
 */
VastlintResult *vastlint_validate(const char *xml, size_t xml_len);

/**
 * Validate a VAST XML string with caller-supplied options.
 *
 * xml               - pointer to a UTF-8 string (null-terminated).
 * xml_len           - byte length (0 → strlen).
 * wrapper_depth     - current wrapper chain depth (0 for the outermost tag).
 * max_wrapper_depth - maximum allowed wrapper chain depth (0 → default 5).
 * rule_overrides    - NULL, or a null-terminated JSON object mapping rule IDs
 *                     to severity strings:
 *                     {"VAST-2.0-mediafile-https":"error","VAST-4.1-mezzanine-recommended":"off"}
 *
 * Returns a pointer to a VastlintResult. The caller MUST free with
 * vastlint_result_free. Returns NULL if xml is NULL.
 */
VastlintResult *vastlint_validate_with_options(const char *xml,
                                               size_t xml_len,
                                               unsigned int wrapper_depth,
                                               unsigned int max_wrapper_depth,
                                               const char *rule_overrides);

/**
 * Return the result as a null-terminated UTF-8 JSON string.
 *
 * The JSON schema:
 * {
 *   "version": "4.2" | null,
 *   "issues": [
 *     {
 *       "id": "VAST-4.2-3.4.1",
 *       "severity": "error" | "warning" | "info",
 *       "message": "...",
 *       "path": "VAST/Ad/InLine/Creatives" | null,
 *       "spec_ref": "IAB VAST 4.2 §3.4.1"
 *     }
 *   ],
 *   "summary": {
 *     "errors": 0,
 *     "warnings": 1,
 *     "infos": 0,
 *     "valid": true
 *   }
 * }
 *
 * The returned pointer is valid until vastlint_result_free is called.
 * Do NOT free the returned pointer directly.
 * Returns NULL if result is NULL.
 */
const char *vastlint_result_json(const VastlintResult *result);

/**
 * Return the number of Error-severity issues. Returns 0 if result is NULL.
 */
size_t vastlint_result_errors(const VastlintResult *result);

/**
 * Return the number of Warning-severity issues. Returns 0 if result is NULL.
 */
size_t vastlint_result_warnings(const VastlintResult *result);

/**
 * Return the number of Info-severity issues. Returns 0 if result is NULL.
 */
size_t vastlint_result_infos(const VastlintResult *result);

/**
 * Return 1 if the result has zero errors, 0 otherwise.
 * Returns 0 if result is NULL.
 */
int vastlint_result_valid(const VastlintResult *result);

/**
 * Free a result pointer returned by vastlint_validate or
 * vastlint_validate_with_options.
 *
 * After this call the pointer is invalid. Passing NULL is safe (no-op).
 */
void vastlint_result_free(VastlintResult *result);

/**
 * Return the vastlint-core version string as a static null-terminated C
 * string. The returned pointer is valid for the lifetime of the process
 * and must NOT be freed.
 */
const char *vastlint_version(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* VASTLINT_H */
